### ISSUE TITLE
"module" or "default"

### ISSUE THREAD

**Issue by guybedford** [zenparsing/node-default-module-proposal#18]
There may be some issues with picking "module" in that for example, file extensions may not be included by default in many packages already providing a "module" field today.

For this reason it may be worth considering a "default" package.json property for uniqueness instead.

See for example react-router which has a "module" property pointing to https://unpkg.com/react-router@4.3.1/es/index.js, in turn using extensionless relative imports.

**Comment by zenparsing** [comment]
Closed via #19
