### ISSUE TITLE
default.js latest stats

### ISSUE THREAD

**Issue by caridy** [zenparsing/node-default-module-proposal#2]
From a total of 116533 pkgs analyzed (only inspecting the "latest versions" of each of those pkgs):
- `default.js` exists in the root of the pkg in 11 of them.
- In 6 of those 11 packages, the value of `"main"` is explicitly set to something else.
- `default.js` is set as main in none of them.

_which means it will be ambiguous in 4 packages_

Alternative, `mod.js` seems to be in a better position:
- exists in 10
- `"main"` set to something else in 3
- set to `"main"` in 6

_which means it is ambiguous in only one of those pkgs._

**Comment by zenparsing** [comment]
What are the names of those 11 packages (if you have that info)?

**Comment by caridy** [comment]
### default.js

appl
brighthas-model
couchdb-expired
couchdb-purge
es6now
esparse
fist.io.logger
grunt-criterion
node-build
zen-cmd
zen-sh

### mod.js

anjita
benchyard
fis-mod
math-buffer
mcpaker
snapp-mod-dust
snapp-mod-ejs
snapp-mod-handlebars
snapp-mod-hogan
snapp-mod-mustache

**Comment by zenparsing** [comment]
These 4:

- es6now
- esparse
- zen-cmd
- zen-sh

are all ES6 entry points (I know because they are my packages), so that just leaves the 7 which would need to be "fixed" to work with require.

**Comment by zenparsing** [comment]
Closing out old threads
