### ISSUE TITLE
why is `.default` required when calling the new form `require.import()`?

### ISSUE THREAD

**Issue by caridy** [zenparsing/node-default-module-proposal#3]
https://github.com/zenparsing/es6-node-modules#gradually-migrating-a-project-to-es-modules

> Gradually migrating a project to ES modules
> Option 2: Replacing require sites

**Comment by zenparsing** [comment]
It depends on what the interface of the upgraded module is, and whether it originally did `module.exports` overriding or not.

**Comment by zenparsing** [comment]
Closing out old threads
