### ISSUE TITLE
Supporting the "module" package.json property

### ISSUE THREAD

**Issue by guybedford** [zenparsing/node-default-module-proposal#7]
The way this proposal handles the "default" could work just as well for the "module" property already in use in the ecosystem by users.

Previously my attempts to work with the "module" property failed (like the In Defense of JS proposal) because it was treating the module property as a package-level flag.

Rather the way this proposal works, would work naturally with the way users already use the "module" property.

Would you be open to a PR to add the adjustment here?

**Comment by guybedford** [comment]
(basically working like the "default" property in the package.json file mentioned here - https://github.com/zenparsing/es6-node-modules/issues/6#issuecomment-395134092)

**Comment by zenparsing** [comment]
Yes, feel free to make a PR and we can discuss any details there.
